[2025-06-16T11:37:30.109+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-16T11:37:30.134+0900] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_ocr_v2.img_preprocess_task manual__2025-06-16T02:37:19.731840+00:00 map_index=2 [queued]>
[2025-06-16T11:37:30.147+0900] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_ocr_v2.img_preprocess_task manual__2025-06-16T02:37:19.731840+00:00 map_index=2 [queued]>
[2025-06-16T11:37:30.147+0900] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-16T11:37:30.161+0900] {taskinstance.py:2890} INFO - Executing <Mapped(_PythonDecoratedOperator): img_preprocess_task> on 2025-06-16 02:37:19.731840+00:00
[2025-06-16T11:37:30.169+0900] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=455) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-16T11:37:30.172+0900] {standard_task_runner.py:72} INFO - Started process 468 to run task
[2025-06-16T11:37:30.174+0900] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_ocr_v2', 'img_preprocess_task', 'manual__2025-06-16T02:37:19.731840+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp6lx0svpw', '--map-index', '2']
[2025-06-16T11:37:30.180+0900] {standard_task_runner.py:105} INFO - Job 76: Subtask img_preprocess_task
[2025-06-16T11:37:30.236+0900] {task_command.py:467} INFO - Running <TaskInstance: image_ocr_v2.img_preprocess_task manual__2025-06-16T02:37:19.731840+00:00 map_index=2 [running]> on host f6d4228a9eb8
[2025-06-16T11:37:30.337+0900] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_ocr_v2' AIRFLOW_CTX_TASK_ID='img_preprocess_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T02:37:19.731840+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T02:37:19.731840+00:00'
[2025-06-16T11:37:30.339+0900] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-16T11:37:30.342+0900] {logging_mixin.py:190} INFO - empty map check {} {'process_id': '_5c388e84-9e1d-4162-ac9c-08e15e753322_pre', 'folder_path': '869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322', 'step_list': [{'name': 'cache', 'param': {'key': 'origin'}}, {'name': 'calc_angle_set1', 'param': {'key': 'angle1', 'iterations': 3}}, {'name': 'save', 'param': {'key': 'rotate1'}}, {'name': 'calc_angle_set2', 'param': {'key': 'angle2', 'iterations': 3}}, {'name': 'save', 'param': {'key': 'rotate2'}}, {'name': 'threshold', 'param': {}}, {'name': 'morphology1', 'param': {}}, {'name': 'scale1', 'param': {'width': 500, 'height': 500}}, {'name': 'save', 'param': {'key': 'classify_preprocess'}}], 'result_file_list': []}
[2025-06-16T11:37:30.343+0900] {logging_mixin.py:190} INFO - step : cache
[2025-06-16T11:37:30.343+0900] {logging_mixin.py:190} INFO - step : calc_angle_set1
[2025-06-16T11:37:30.412+0900] {logging_mixin.py:190} INFO - angle1 :  0 0.6774876878916665 -89.18955880578811 -89.18911768819981 90.52415507024762 90.56447217530697
[2025-06-16T11:37:30.505+0900] {logging_mixin.py:190} INFO - angle2 :  0.6774876878916665 0.017450961644254193 -89.87530862011141 -89.81296329926546 89.87895275858736 89.87912300736653
[2025-06-16T11:37:30.506+0900] {logging_mixin.py:190} INFO - step : save
[2025-06-16T11:37:30.716+0900] {logging_mixin.py:190} INFO - file_copy: /opt/***/data/temp/869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322/rotate1.png
[2025-06-16T11:37:30.735+0900] {logging_mixin.py:190} INFO - step : calc_angle_set2
[2025-06-16T11:37:36.787+0900] {logging_mixin.py:190} INFO - file_copy: /opt/***/data/temp/869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322/rotate2_1.png
[2025-06-16T11:37:38.288+0900] {logging_mixin.py:190} INFO - osd 1 270 270 3.58 Latin 0.56
[2025-06-16T11:37:44.365+0900] {logging_mixin.py:190} INFO - file_copy: /opt/***/data/temp/869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322/rotate2_2.png
[2025-06-16T11:37:45.701+0900] {logging_mixin.py:190} INFO - osd 2 450 180 3.86 Latin 0.8
[2025-06-16T11:37:51.679+0900] {logging_mixin.py:190} INFO - file_copy: /opt/***/data/temp/869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322/rotate2_3.png
[2025-06-16T11:37:53.162+0900] {logging_mixin.py:190} INFO - step : save
[2025-06-16T11:37:53.308+0900] {logging_mixin.py:190} INFO - file_copy: /opt/***/data/temp/869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322/rotate2.png
[2025-06-16T11:37:53.320+0900] {logging_mixin.py:190} INFO - step : threshold
[2025-06-16T11:37:53.394+0900] {logging_mixin.py:190} INFO - step : morphology1
[2025-06-16T11:37:53.408+0900] {logging_mixin.py:190} INFO - step : scale1
[2025-06-16T11:37:53.414+0900] {logging_mixin.py:190} INFO - step : save
[2025-06-16T11:37:53.422+0900] {logging_mixin.py:190} INFO - file_copy: /opt/***/data/temp/869516f8-0dd8-4c8c-913c-40afe0f54c39/5c388e84-9e1d-4162-ac9c-08e15e753322/classify_preprocess.png
[2025-06-16T11:37:53.424+0900] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/img_preprocess_task.py", line 60, in img_preprocess_task
    file_info.setdefault(key, {}).append(result_map)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
[2025-06-16T11:37:53.433+0900] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=image_ocr_v2, task_id=img_preprocess_task, run_id=manual__2025-06-16T02:37:19.731840+00:00, map_index=2, execution_date=20250616T023719, start_date=20250616T023730, end_date=20250616T023753
[2025-06-16T11:37:53.452+0900] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-16T11:37:53.453+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task img_preprocess_task ('dict' object has no attribute 'append'; 468)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/img_preprocess_task.py", line 60, in img_preprocess_task
    file_info.setdefault(key, {}).append(result_map)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
[2025-06-16T11:37:53.476+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-16T11:37:53.488+0900] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T11:37:53.489+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
