[2025-06-25T14:23:53.748+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-25T14:23:53.812+0900] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_classify_v1.init_task manual__2025-06-25T05:23:48.044934+00:00 [queued]>
[2025-06-25T14:23:53.846+0900] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_classify_v1.init_task manual__2025-06-25T05:23:48.044934+00:00 [queued]>
[2025-06-25T14:23:53.848+0900] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-25T14:23:53.901+0900] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): init_task> on 2025-06-25 05:23:48.044934+00:00
[2025-06-25T14:23:53.941+0900] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=86789) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-25T14:23:53.948+0900] {standard_task_runner.py:72} INFO - Started process 86806 to run task
[2025-06-25T14:23:53.951+0900] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_classify_v1', 'init_task', 'manual__2025-06-25T05:23:48.044934+00:00', '--job-id', '5269', '--raw', '--subdir', 'DAGS_FOLDER/img_classify_dag.py', '--cfg-path', '/tmp/tmpq5kevfzn']
[2025-06-25T14:23:53.963+0900] {standard_task_runner.py:105} INFO - Job 5269: Subtask init_task
[2025-06-25T14:23:54.149+0900] {task_command.py:467} INFO - Running <TaskInstance: image_classify_v1.init_task manual__2025-06-25T05:23:48.044934+00:00 [running]> on host f6d4228a9eb8
[2025-06-25T14:23:54.493+0900] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_classify_v1' AIRFLOW_CTX_TASK_ID='init_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T05:23:48.044934+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T05:23:48.044934+00:00'
[2025-06-25T14:23:54.499+0900] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-25T14:23:54.540+0900] {base.py:84} INFO - Retrieving connection 'maria_db_conn'
[2025-06-25T14:23:54.583+0900] {python.py:240} INFO - Done. Returned value was: None
[2025-06-25T14:23:54.623+0900] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-25T14:23:54.626+0900] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=image_classify_v1, task_id=init_task, run_id=manual__2025-06-25T05:23:48.044934+00:00, execution_date=20250625T052348, start_date=20250625T052353, end_date=20250625T052354
[2025-06-25T14:23:54.792+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-25T14:23:54.974+0900] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-25T14:23:54.984+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
