[2025-06-16T19:09:27.721+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-16T19:09:27.733+0900] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_ocr_v2.check_file_exists_branch manual__2025-06-16T10:09:25.713690+00:00 [queued]>
[2025-06-16T19:09:27.740+0900] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_ocr_v2.check_file_exists_branch manual__2025-06-16T10:09:25.713690+00:00 [queued]>
[2025-06-16T19:09:27.741+0900] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-16T19:09:27.753+0900] {taskinstance.py:2890} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_file_exists_branch> on 2025-06-16 10:09:25.713690+00:00
[2025-06-16T19:09:27.761+0900] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=13769) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-16T19:09:27.763+0900] {standard_task_runner.py:72} INFO - Started process 13771 to run task
[2025-06-16T19:09:27.763+0900] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_ocr_v2', 'check_file_exists_branch', 'manual__2025-06-16T10:09:25.713690+00:00', '--job-id', '737', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp390_w654']
[2025-06-16T19:09:27.766+0900] {standard_task_runner.py:105} INFO - Job 737: Subtask check_file_exists_branch
[2025-06-16T19:09:27.885+0900] {task_command.py:467} INFO - Running <TaskInstance: image_ocr_v2.check_file_exists_branch manual__2025-06-16T10:09:25.713690+00:00 [running]> on host f6d4228a9eb8
[2025-06-16T19:09:28.212+0900] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_ocr_v2' AIRFLOW_CTX_TASK_ID='check_file_exists_branch' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T10:09:25.713690+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T10:09:25.713690+00:00'
[2025-06-16T19:09:28.217+0900] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-16T19:09:28.233+0900] {python.py:240} INFO - Done. Returned value was: get_file_info_list_task
[2025-06-16T19:09:28.234+0900] {branch.py:38} INFO - Branch into get_file_info_list_task
[2025-06-16T19:09:28.237+0900] {skipmixin.py:233} INFO - Following branch ('get_file_info_list_task',)
[2025-06-16T19:09:28.271+0900] {skipmixin.py:281} INFO - Skipping tasks [('end_task', -1)]
[2025-06-16T19:09:28.385+0900] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-16T19:09:28.387+0900] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=image_ocr_v2, task_id=check_file_exists_branch, run_id=manual__2025-06-16T10:09:25.713690+00:00, execution_date=20250616T100925, start_date=20250616T100927, end_date=20250616T100928
[2025-06-16T19:09:28.522+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-16T19:09:28.671+0900] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-16T19:09:28.680+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
