[2025-05-26T05:30:36.608+0000] {processor.py:186} INFO - Started process (PID=3198) to work on /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:30:36.610+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag copy.py for tasks to queue
[2025-05-26T05:30:36.611+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:30:36.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:30:36.638+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:30:36.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag copy.py", line 1, in <module>
    from airflow.sdk import dag
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-05-26T05:30:36.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:30:36.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag copy.py took 0.060 seconds
[2025-05-26T05:31:06.797+0000] {processor.py:186} INFO - Started process (PID=3263) to work on /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:31:06.798+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag copy.py for tasks to queue
[2025-05-26T05:31:06.799+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:31:06.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:31:06.815+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:31:06.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag copy.py", line 1, in <module>
    from airflow.sdk import dag
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-05-26T05:31:06.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:31:06.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag copy.py took 0.045 seconds
[2025-05-26T05:31:37.407+0000] {processor.py:186} INFO - Started process (PID=3323) to work on /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:31:37.408+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag copy.py for tasks to queue
[2025-05-26T05:31:37.410+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:31:37.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:31:37.431+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:31:37.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag copy.py", line 1, in <module>
    from airflow.sdk import dag
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-05-26T05:31:37.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:31:37.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag copy.py took 0.058 seconds
[2025-05-26T05:32:07.852+0000] {processor.py:186} INFO - Started process (PID=3388) to work on /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:32:07.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag copy.py for tasks to queue
[2025-05-26T05:32:07.854+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:32:07.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:32:07.873+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:32:07.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag copy.py", line 1, in <module>
    from airflow.sdk import dag
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-05-26T05:32:07.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:32:07.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag copy.py took 0.048 seconds
[2025-05-26T05:32:38.499+0000] {processor.py:186} INFO - Started process (PID=3453) to work on /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:32:38.500+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test_dag copy.py for tasks to queue
[2025-05-26T05:32:38.501+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:32:38.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:32:38.519+0000] {logging_mixin.py:190} INFO - [2025-05-26T05:32:38.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test_dag copy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag copy.py", line 1, in <module>
    from airflow.sdk import dag
ModuleNotFoundError: No module named 'airflow.sdk'
[2025-05-26T05:32:38.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag copy.py
[2025-05-26T05:32:38.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test_dag copy.py took 0.058 seconds
