[2025-06-09T07:03:09.707+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-09T07:03:09.732+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: image_ocr_v2.check_file_exists_branch manual__2025-06-09T07:03:07.238023+00:00 [queued]>
[2025-06-09T07:03:09.756+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: image_ocr_v2.check_file_exists_branch manual__2025-06-09T07:03:07.238023+00:00 [queued]>
[2025-06-09T07:03:09.757+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-06-09T07:03:09.807+0000] {taskinstance.py:2890} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_file_exists_branch> on 2025-06-09 07:03:07.238023+00:00
[2025-06-09T07:03:09.827+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4884) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-09T07:03:09.834+0000] {standard_task_runner.py:72} INFO - Started process 4886 to run task
[2025-06-09T07:03:09.835+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'image_ocr_v2', 'check_file_exists_branch', 'manual__2025-06-09T07:03:07.238023+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpjnh920kt']
[2025-06-09T07:03:09.845+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask check_file_exists_branch
[2025-06-09T07:03:10.004+0000] {task_command.py:467} INFO - Running <TaskInstance: image_ocr_v2.check_file_exists_branch manual__2025-06-09T07:03:07.238023+00:00 [running]> on host 85194d6fbd18
[2025-06-09T07:03:10.330+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='image_ocr_v2' AIRFLOW_CTX_TASK_ID='check_file_exists_branch' AIRFLOW_CTX_EXECUTION_DATE='2025-06-09T07:03:07.238023+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-09T07:03:07.238023+00:00'
[2025-06-09T07:03:10.335+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-09T07:03:10.351+0000] {python.py:240} INFO - Done. Returned value was: get_file_info_list_task
[2025-06-09T07:03:10.353+0000] {branch.py:38} INFO - Branch into get_file_info_list_task
[2025-06-09T07:03:10.356+0000] {skipmixin.py:233} INFO - Following branch ('get_file_info_list_task',)
[2025-06-09T07:03:10.389+0000] {skipmixin.py:281} INFO - Skipping tasks [('end_task', -1)]
[2025-06-09T07:03:10.499+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-09T07:03:10.501+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=image_ocr_v2, task_id=check_file_exists_branch, run_id=manual__2025-06-09T07:03:07.238023+00:00, execution_date=20250609T070307, start_date=20250609T070309, end_date=20250609T070310
[2025-06-09T07:03:10.636+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-09T07:03:10.777+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-09T07:03:10.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
